// <auto-generated />
using System;
using HomeServicesPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeServicesPortal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810095346_AddCancelRejectReasons")]
    partial class AddCancelRejectReasons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeServicesPortal.Entities.Client", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<string>("Cnic")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("CNIC");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserUid")
                        .HasColumnType("int")
                        .HasColumnName("UserUID");

                    b.HasKey("Uid");

                    b.HasIndex("UserUid")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.ClientAddress", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<string>("AddressTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ClientUid")
                        .HasColumnType("int")
                        .HasColumnName("ClientUID");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10,7)");

                    b.HasKey("Uid");

                    b.HasIndex("ClientUid");

                    b.ToTable("ClientAddresses", (string)null);
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.CommissionRule", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<int?>("CategoryUid")
                        .HasColumnType("int")
                        .HasColumnName("CategoryUID");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("ProviderUid")
                        .HasColumnType("int")
                        .HasColumnName("ProviderUID");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Uid");

                    b.HasIndex("CategoryUid");

                    b.HasIndex("ProviderUid");

                    b.ToTable("CommissionRules", (string)null);
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.CustomerServiceRequest", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CategoryUid")
                        .HasColumnType("int")
                        .HasColumnName("CategoryUID");

                    b.Property<int>("ClientAddressUid")
                        .HasColumnType("int")
                        .HasColumnName("ClientAddressUID");

                    b.Property<int>("ClientUid")
                        .HasColumnType("int")
                        .HasColumnName("ClientUID");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("EstimatedBudget")
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("IsUrgent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("PreferredServiceDate")
                        .HasColumnType("date");

                    b.Property<string>("PreferredServiceTime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ServiceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Uid");

                    b.HasIndex("CategoryUid");

                    b.HasIndex("ClientAddressUid");

                    b.HasIndex("ClientUid");

                    b.ToTable("CustomerServiceRequests", (string)null);
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.PaymentLedger", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("BookingUid")
                        .HasColumnType("int")
                        .HasColumnName("BookingUID");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ProviderUid")
                        .HasColumnType("int")
                        .HasColumnName("ProviderUID");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Uid");

                    b.HasIndex("BookingUid");

                    b.HasIndex("ProviderUid");

                    b.ToTable("PaymentLedger", (string)null);
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.Provider", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<string>("AvailableTiming")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AvailableTiming");

                    b.Property<decimal>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("CategoryUid")
                        .HasColumnType("int")
                        .HasColumnName("CategoryUID");

                    b.Property<string>("Cnic")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("CNIC");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExperienceYears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("TotalJobsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UserUid")
                        .HasColumnType("int")
                        .HasColumnName("UserUID");

                    b.HasKey("Uid");

                    b.HasIndex("CategoryUid");

                    b.HasIndex("UserUid")
                        .IsUnique();

                    b.ToTable("Providers", (string)null);
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.ProviderDocument", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<string>("CnicBackImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CNICBackImagePath");

                    b.Property<string>("CnicFrontImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CNICFrontImagePath");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ProfilePhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProviderUid")
                        .HasColumnType("int")
                        .HasColumnName("ProviderUID");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("VerificationRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("VerifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerifiedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Uid");

                    b.HasIndex("ProviderUid")
                        .IsUnique()
                        .HasDatabaseName("UQ_ProviderDocuments_ProviderUID");

                    b.ToTable("ProviderDocuments", (string)null);
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.ProviderPayout", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Method")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PaidOn")
                        .HasColumnType("datetime");

                    b.Property<int>("ProviderUid")
                        .HasColumnType("int")
                        .HasColumnName("ProviderUID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Uid");

                    b.HasIndex("ProviderUid");

                    b.ToTable("ProviderPayouts", (string)null);
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.Service", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Uid");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.ServiceBooking", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<DateTime?>("AcceptedOn")
                        .HasColumnType("datetime");

                    b.Property<decimal>("AdditionalCharges")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ClientUid")
                        .HasColumnType("int")
                        .HasColumnName("ClientUID");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("CommissionType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("CommissionValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("CustomerPaid")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("CustomerRemaining")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Deductions")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("EstimatedAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Passcode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("ProviderEarning")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("ProviderUid")
                        .HasColumnType("int")
                        .HasColumnName("ProviderUID");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequestUid")
                        .HasColumnType("int")
                        .HasColumnName("RequestUID");

                    b.Property<string>("ServiceDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Completed");

                    b.Property<decimal>("VisitCharges")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Uid");

                    b.HasIndex("ClientUid");

                    b.HasIndex("ProviderUid");

                    b.HasIndex("RequestUid");

                    b.ToTable("ServiceBookings", (string)null);
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.ServiceCategory", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ServiceUid")
                        .HasColumnType("int")
                        .HasColumnName("ServiceUID");

                    b.HasKey("Uid");

                    b.HasIndex("ServiceUid");

                    b.ToTable("ServiceCategories", (string)null);
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.ServiceTitle", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<int>("CategoryUid")
                        .HasColumnType("int")
                        .HasColumnName("CategoryUID");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Uid");

                    b.HasIndex("CategoryUid");

                    b.ToTable("ServiceTitles", (string)null);
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.Staff", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("UserUid")
                        .HasColumnType("int")
                        .HasColumnName("UserUID");

                    b.HasKey("Uid");

                    b.HasIndex("UserUid")
                        .IsUnique();

                    b.ToTable("Staff", (string)null);
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.UserOTP", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OTPCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OTPType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("VerifiedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Uid");

                    b.HasIndex("IsVerified");

                    b.HasIndex("MobileNo");

                    b.ToTable("UserOTP", (string)null);
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.UsersLogin", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Uid");

                    b.HasIndex("MobileNo")
                        .IsUnique();

                    b.ToTable("UsersLogin", (string)null);
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.Client", b =>
                {
                    b.HasOne("HomeServicesPortal.Entities.UsersLogin", "User")
                        .WithOne("Client")
                        .HasForeignKey("HomeServicesPortal.Entities.Client", "UserUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Clients_UsersLogin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.ClientAddress", b =>
                {
                    b.HasOne("HomeServicesPortal.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ClientAddresses_Clients");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.CommissionRule", b =>
                {
                    b.HasOne("HomeServicesPortal.Entities.ServiceCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CommissionRules_ServiceCategories");

                    b.HasOne("HomeServicesPortal.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CommissionRules_Providers");

                    b.Navigation("Category");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.CustomerServiceRequest", b =>
                {
                    b.HasOne("HomeServicesPortal.Entities.ServiceCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CustomerServiceRequests_ServiceCategories");

                    b.HasOne("HomeServicesPortal.Entities.ClientAddress", "ClientAddress")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("ClientAddressUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CustomerServiceRequests_ClientAddresses");

                    b.HasOne("HomeServicesPortal.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CustomerServiceRequests_Clients");

                    b.Navigation("Category");

                    b.Navigation("Client");

                    b.Navigation("ClientAddress");
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.PaymentLedger", b =>
                {
                    b.HasOne("HomeServicesPortal.Entities.ServiceBooking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PaymentLedger_ServiceBookings");

                    b.HasOne("HomeServicesPortal.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PaymentLedger_Providers");

                    b.Navigation("Booking");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.Provider", b =>
                {
                    b.HasOne("HomeServicesPortal.Entities.ServiceCategory", "Category")
                        .WithMany("Providers")
                        .HasForeignKey("CategoryUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Providers_ServiceCategories");

                    b.HasOne("HomeServicesPortal.Entities.UsersLogin", "User")
                        .WithOne("Provider")
                        .HasForeignKey("HomeServicesPortal.Entities.Provider", "UserUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Providers_UsersLogin");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.ProviderDocument", b =>
                {
                    b.HasOne("HomeServicesPortal.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProviderDocuments_Providers");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.ProviderPayout", b =>
                {
                    b.HasOne("HomeServicesPortal.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ProviderPayouts_Providers");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.ServiceBooking", b =>
                {
                    b.HasOne("HomeServicesPortal.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceBookings_Clients");

                    b.HasOne("HomeServicesPortal.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceBookings_Providers");

                    b.HasOne("HomeServicesPortal.Entities.CustomerServiceRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceBookings_CustomerServiceRequests");

                    b.Navigation("Client");

                    b.Navigation("Provider");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.ServiceCategory", b =>
                {
                    b.HasOne("HomeServicesPortal.Entities.Service", "Service")
                        .WithMany("Categories")
                        .HasForeignKey("ServiceUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceCategories_Services");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.ServiceTitle", b =>
                {
                    b.HasOne("HomeServicesPortal.Entities.ServiceCategory", "Category")
                        .WithMany("Titles")
                        .HasForeignKey("CategoryUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceTitles_ServiceCategories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.Staff", b =>
                {
                    b.HasOne("HomeServicesPortal.Entities.UsersLogin", "User")
                        .WithOne("Staff")
                        .HasForeignKey("HomeServicesPortal.Entities.Staff", "UserUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Staff_UsersLogin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.ClientAddress", b =>
                {
                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.Service", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.ServiceCategory", b =>
                {
                    b.Navigation("Providers");

                    b.Navigation("Titles");
                });

            modelBuilder.Entity("HomeServicesPortal.Entities.UsersLogin", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("Provider");

                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
